// Generated by CoffeeScript 1.12.2
(function() {
  var adapt, makePromise,
    slice = [].slice;

  makePromise = require("make-promise");

  module.exports = adapt = function(fn, receiver) {
    return function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return makePromise(function(cb) {
        args.push(cb);
        return fn.apply(receiver, args);
      });
    };
  };

}).call(this);

//# sourceMappingURL=adapt.js.map
