// Generated by CoffeeScript 1.6.2
(function() {
  var collect, collectProperties, collectValues, each, ensurePromise, fail, fulfill, getTypeOf, _ref;

  _ref = require("./utilities"), fulfill = _ref.fulfill, fail = _ref.fail, ensurePromise = _ref.ensurePromise;

  each = require("./each");

  module.exports = collect = function(value) {
    switch (getTypeOf(value)) {
      case "object":
        if (typeof value.then === "function") {
          return value;
        }
        return collectProperties(value);
      case "array":
        return collectValues(value);
      default:
        return fail(new Error("You can only collect arrays or objects."));
    }
  };

  collectValues = function(array) {
    var results;

    results = [];
    return each(array, ensurePromise, {
      handleResult: function(value, i) {
        return results[i] = value;
      },
      getFinalValue: function() {
        return results;
      }
    });
  };

  collectProperties = function(object) {
    var name, names, newProperties, value, values;

    names = Object.keys(object);
    values = (function() {
      var _results;

      _results = [];
      for (name in object) {
        value = object[name];
        _results.push(value);
      }
      return _results;
    })();
    newProperties = {};
    return each(values, ensurePromise, {
      handleResult: function(value, i) {
        return newProperties[names[i]] = value;
      },
      getFinalValue: function() {
        return newProperties;
      }
    });
  };

  getTypeOf = (function() {
    var classToType, name, _i, _len, _ref1;

    classToType = {};
    _ref1 = "Boolean Number String Function Array Date RegExp Undefined Null".split(" ");
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      name = _ref1[_i];
      classToType["[object " + name + "]"] = name.toLowerCase();
    }
    return function(obj) {
      var strType;

      strType = Object.prototype.toString.call(obj);
      return classToType[strType] || "object";
    };
  })();

}).call(this);

/*
//@ sourceMappingURL=collect.map
*/
