// Generated by CoffeeScript 1.12.2
(function() {
  var collect, getTypeOf, isPromise, makePromise;

  isPromise = require("./utilities").isPromise;

  makePromise = require("make-promise");

  module.exports = collect = function(inputs) {
    if (isPromise(inputs)) {
      return inputs;
    }
    return makePromise(function(cb) {
      var err, i, indexes, j, key, len, numRemaining, outputs, promise, promises, resolver, value;
      switch (getTypeOf(inputs)) {
        case "object":
          outputs = {};
          break;
        case "array":
          outputs = new Array(inputs.length);
          break;
        default:
          return cb(new Error("You can only collect arrays or objects."));
      }
      promises = [];
      indexes = [];
      for (key in inputs) {
        value = inputs[key];
        if (isPromise(value)) {
          promises.push(value);
          indexes.push(key);
        } else {
          outputs[key] = value;
        }
      }
      if (!(promises.length > 0)) {
        return cb(null, outputs);
      }
      numRemaining = promises.length;
      resolver = function(i) {
        return function(result) {
          outputs[indexes[i]] = result;
          numRemaining--;
          if (!(numRemaining > 0)) {
            return cb(null, outputs);
          }
        };
      };
      for (i = j = 0, len = promises.length; j < len; i = ++j) {
        promise = promises[i];
        try {
          promise.then(resolver(i), function(err) {
            return cb(err);
          });
        } catch (error) {
          err = error;
          return cb(err);
        }
      }
    });
  };

  getTypeOf = (function() {
    var classToType, j, len, name, ref;
    classToType = {};
    ref = "Boolean Number String Function Array Date RegExp Undefined Null".split(" ");
    for (j = 0, len = ref.length; j < len; j++) {
      name = ref[j];
      classToType["[object " + name + "]"] = name.toLowerCase();
    }
    return function(obj) {
      var strType;
      strType = Object.prototype.toString.call(obj);
      return classToType[strType] || "object";
    };
  })();

}).call(this);

//# sourceMappingURL=collect.js.map
