// Generated by CoffeeScript 1.6.2
(function() {
  var each, makePromise;

  makePromise = require("make-promise");

  module.exports = each = function(values, iterator, options) {
    if (options == null) {
      options = {};
    }
    return makePromise(function(cb) {
      var error, i, numRemaining, promise, promises, resolver, stopped, value, _i, _len, _results;

      if (!values.length) {
        return cb(null, typeof options.getFinalValue === "function" ? options.getFinalValue() : void 0);
      }
      try {
        promises = (function() {
          var _i, _len, _results;

          _results = [];
          for (_i = 0, _len = values.length; _i < _len; _i++) {
            value = values[_i];
            _results.push(iterator(value));
          }
          return _results;
        })();
      } catch (_error) {
        error = _error;
        return cb(error);
      }
      stopped = false;
      numRemaining = promises.length;
      resolver = function(index) {
        return function(value) {
          if (stopped) {
            return;
          }
          try {
            if (typeof options.handleResult === "function") {
              options.handleResult(value, index);
            }
          } catch (_error) {
            error = _error;
            stopped = true;
            return cb(error);
          }
          numRemaining--;
          if (numRemaining === 0 || (typeof options.stopEarly === "function" ? options.stopEarly() : void 0)) {
            stopped = true;
            return cb(null, typeof options.getFinalValue === "function" ? options.getFinalValue() : void 0);
          }
        };
      };
      _results = [];
      for (i = _i = 0, _len = promises.length; _i < _len; i = ++_i) {
        promise = promises[i];
        try {
          _results.push(promise.then(resolver(i), function(error) {
            return cb(error);
          }));
        } catch (_error) {
          error = _error;
          cb(error);
          _results.push(stopped = true);
        }
      }
      return _results;
    });
  };

}).call(this);

/*
//@ sourceMappingURL=each.map
*/
