// Generated by CoffeeScript 1.6.2
(function() {
  var each, eachSeries;

  each = require("./each");

  module.exports = eachSeries = function(values, iterator, options) {
    if (options == null) {
      options = {};
    }
    options.concurrency = 1;
    return each(values, iterator, options);
  };

}).call(this);

/*
//@ sourceMappingURL=eachSeries.map
*/
