// Generated by CoffeeScript 1.12.2
(function() {
  var each, eachLimit;

  each = require("./each");

  module.exports = eachLimit = function(values, concurrency, iterator, options) {
    if (options == null) {
      options = {};
    }
    options.concurrency = concurrency;
    return each(values, iterator, options);
  };

}).call(this);

//# sourceMappingURL=eachLimit.js.map
