// Generated by CoffeeScript 1.6.2
(function() {
  var faithful, fn, moduleName, name, _i, _len, _ref, _ref1;

  module.exports = faithful = {
    adapt: require("./adapt"),
    each: require("./each"),
    forEach: require("./each"),
    eachSeries: require("./eachSeries"),
    forEachSeries: require("./eachSeries"),
    adapt: require("./adapt"),
    makePromise: require("make-promise"),
    collect: require("./collect"),
    throwHard: require("./throwHard")
  };

  _ref = ['utilities', 'collections', 'flow-control'];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    moduleName = _ref[_i];
    _ref1 = require("./" + moduleName);
    for (name in _ref1) {
      fn = _ref1[name];
      faithful[name] = fn;
    }
  }

}).call(this);

/*
//@ sourceMappingURL=faithful.map
*/
