// Generated by CoffeeScript 1.6.2
(function() {
  var map, mapSeries, _ref,
    __slice = [].slice;

  _ref = require('./collections'), map = _ref.map, mapSeries = _ref.mapSeries;

  module.exports = {
    series: function(functions) {
      return mapSeries(functions, function(fn) {
        return fn();
      });
    },
    parallel: function(functions) {
      return map(functions, function(fn) {
        return fn();
      });
    },
    applyToEach: function() {
      var args, functions;

      functions = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return map(functions, function(fn) {
        return fn.apply({}, args);
      });
    },
    applyToEachSeries: function() {
      var args, functions;

      functions = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return mapSeries(functions, function(fn) {
        return fn.apply({}, args);
      });
    }
  };

}).call(this);

/*
//@ sourceMappingURL=flow-control.map
*/
