// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(err) {
    var error;

    if (typeof err === "string" || err instanceof String) {
      err = new Error(err);
    }
    if (!(err instanceof Error)) {
      err = new Error("Non-string, non-Error error.");
    }
    try {
      throw new Error(err);
    } catch (_error) {
      error = _error;
      setImmediate(function() {
        console.error("");
        console.error(error.stack);
        process.exit(1);
        throw error;
      });
    }
    throw err;
  };

}).call(this);

/*
//@ sourceMappingURL=throwHard.map
*/
